In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory

import os
print(os.listdir("../input"))

# Any results you write to the current directory are saved as output.

['tag.csv', 'genome_scores.csv', 'rating.csv', 'link.csv', 'genome_tags.csv', 'movie.csv']

In [2]:
movie = pd.read_csv("../input/movie.csv")
movie.columns

Index(['movieId', 'title', 'genres'], dtype='object')

In [3]:
movie = movie.loc[:,["movieId","title"]]
movie.head(10)

   movieId                               title
0        1                    Toy Story (1995)
1        2                      Jumanji (1995)
2        3             Grumpier Old Men (1995)
3        4            Waiting to Exhale (1995)
4        5  Father of the Bride Part II (1995)
5        6                         Heat (1995)
6        7                      Sabrina (1995)
7        8                 Tom and Huck (1995)
8        9                 Sudden Death (1995)
9       10                    GoldenEye (1995)

In [4]:
# import rating data and look at columsn
rating = pd.read_csv("../input/rating.csv")
rating.columns

Index(['userId', 'movieId', 'rating', 'timestamp'], dtype='object')

In [5]:
rating = rating.loc[:,["userId","movieId","rating"]]
rating.head(10)

   userId  movieId  rating
0       1        2     3.5
1       1       29     3.5
2       1       32     3.5
3       1       47     3.5
4       1       50     3.5
5       1      112     3.5
6       1      151     4.0
7       1      223     4.0
8       1      253     4.0
9       1      260     4.0

In [6]:
data = pd.merge(movie,rating)

In [7]:
data.head(10)

   movieId             title  userId  rating
0        1  Toy Story (1995)       3     4.0
1        1  Toy Story (1995)       6     5.0
2        1  Toy Story (1995)       8     4.0
3        1  Toy Story (1995)      10     4.0
4        1  Toy Story (1995)      11     4.5
5        1  Toy Story (1995)      12     4.0
6        1  Toy Story (1995)      13     4.0
7        1  Toy Story (1995)      14     4.5
8        1  Toy Story (1995)      16     3.0
9        1  Toy Story (1995)      19     5.0

In [8]:
data.shape

(20000263, 4)

In [9]:
data = data.iloc[:1000000,:]

In [10]:
pivot_table = data.pivot_table(index=["userId"],columns=["title"],values="rating")
pivot_table.head(10)

title   Ace Ventura: When Nature Calls (1995)                  ...                    Young Poisoner's Handbook, The (1995)
userId                                                         ...
1                                         NaN                  ...                                                      NaN
2                                         NaN                  ...                                                      NaN
3                                         NaN                  ...                                                      NaN
4                                         3.0                  ...                                                      NaN
5                                         NaN                  ...                                                      NaN
6                                         NaN                  ...                                                      NaN
7                                         NaN                  ...                                                      NaN
8                                         1.0                  ...                                                      NaN
10                                        NaN                  ...                                                      NaN
11                                        3.5                  ...                                                      NaN

[10 rows x 146 columns]

In [11]:
movie_watched = pivot_table["Bad Boys (1995)"]
similarity_with_other_movies = pivot_table.corrwith(movie_watched)  # find correlation between "Bad Boys (1995)" and other movies
similarity_with_other_movies = similarity_with_other_movies.sort_values(ascending=False)
similarity_with_other_movies.head()

title
Bad Boys (1995)                        1.000000
Headless Body in Topless Bar (1995)    0.723747
Last Summer in the Hamptons (1995)     0.607554
Two Bits (1995)                        0.507008
Shadows (Cienie) (1988)                0.494186
dtype: float64